# -----------------------------------------------------------------------------
# ./rom/ramen_timer.tdxをロードし、実行開始(Gコマンド)からブザー吹鳴までの時間
# が3分15秒に可能な限り近付くように WAIT の値を調整してください。
#
# WAIT の値が大きいほど処理が遅くなります。
# デフォルトの記述は、作者の環境での設定値ですので参考にしてください。
#
# #から改行まではコメントとして扱われます。
# -----------------------------------------------------------------------------

# WAIT 47  # X68000 実機 用 (CompactXVI 10MHz にて確認)

WAIT   46  # X68000 Z / XM6 TypeG 用調整値
